const commentData = [
  {
    id: 1,
    name: 'Jackyboy',
    iconImage: 'https://i.pravatar.cc/150?img=12',
    comment: 'Looking gorgeous babe 😍 Absolute stunner',
    time: '2h',
    like: 2,
  },
  {
    id: 2,
    name: 'Sophia',
    iconImage: 'https://i.pravatar.cc/150?img=47',
    comment: 'This look is absolutely amazing 🔥',
    time: '3h',
    like: 8,
  },
  {
    id: 3,
    name: 'Ryan',
    iconImage: 'https://i.pravatar.cc/150?img=11',
    comment: 'Okayyy, this is such a vibe 😍',
    time: '4h',
    like: 5,
  },
  {
    id: 4,
    name: 'Emma',
    iconImage: 'https://i.pravatar.cc/150?img=44',
    comment: 'You are glowing ✨ Looking beautiful!',
    time: '5h',
    like: 12,
  },
  {
    id: 5,
    name: 'Alex',
    iconImage: 'https://i.pravatar.cc/150?img=13',
    comment: 'Absolutely love this picture ❤️',
    time: '6h',
    like: 7,
  },
  {
    id: 6,
    name: 'Mia',
    iconImage: 'https://i.pravatar.cc/150?img=45',
    comment: 'Too cute 😍 Where is this place?',
    time: '8h',
    like: 4,
  },
  {
    id: 7,
    name: 'Daniel',
    iconImage: 'https://i.pravatar.cc/150?img=14',
    comment: 'That smile though! ❤️🔥',
    time: '10h',
    like: 15,
  },
  {
    id: 8,
    name: 'Olivia',
    iconImage: 'https://i.pravatar.cc/150?img=48',
    comment: 'Such a beautiful shot 📸✨',
    time: '12h',
    like: 9,
  },
  {
    id: 9,
    name: 'Chris',
    iconImage: 'https://i.pravatar.cc/150?img=15',
    comment: 'Looking fantastic as always 🔥',
    time: '1d',
    like: 6,
  },
  {
    id: 10,
    name: 'Ava',
    iconImage: 'https://i.pravatar.cc/150?img=49',
    comment: 'Wowww 😍 This is seriously gorgeous!',
    time: '1d',
    like: 18,
  },
];

export default commentData;