const postData = [
  {
    id: 1,
    catg: 'single',
    name: 'CrazyForYou',
    iconImage: 'https://i.pravatar.cc/150?img=1',
    deatail: 'Private shoot done today, what do you guys think?',
    likeCount: '245',
    postTime: '5 minutes ago',
    comments: ['hii', 'hello', 'what is going on', 'hii', 'hn'],
  },
  {
    id: 2,
    catg: 'couple',
    name: 'LoveBirds',
    iconImage: 'https://i.pravatar.cc/150?img=2',
    deatail: 'A beautiful evening with my favorite person ❤️',
    postImage: 'https://picsum.photos/800/600?random=2',
    likeCount: '189',
    postTime: '18 minutes ago',
    comments: ['Beautiful couple ❤️', 'So cute!', 'Lovely', 'Amazing moment'],
  },
  {
    id: 3,
    catg: 'single',
    name: 'MysteryGirl',
    iconImage: 'https://i.pravatar.cc/150?img=3',
    deatail: 'Just enjoying my own company today ✨',
    postImage: 'https://picsum.photos/800/600?random=3',
    likeCount: '324',
    postTime: '32 minutes ago',
    comments: ['Looking good!', 'Nice vibes ✨', 'Beautiful', 'Wow'],
  },
  {
    id: 4,
    catg: 'couple',
    name: 'CrazyLove',
    iconImage: 'https://i.pravatar.cc/150?img=4',
    deatail: 'Some moments are simply perfect when you are together ❤️',
    postImage: 'https://picsum.photos/800/600?random=4',
    likeCount: '512',
    postTime: '1 hour ago',
    comments: ['Perfect ❤️', 'So lovely', 'Cute couple', 'Beautiful picture'],
  },
  {
    id: 5,
    catg: 'single',
    name: 'PrettySoul',
    iconImage: 'https://i.pravatar.cc/150?img=5',
    deatail: 'Feeling confident and happy today 💫',
    postImage: 'https://picsum.photos/800/600?random=5',
    likeCount: '278',
    postTime: '2 hours ago',
    comments: ['Looking amazing', 'Beautiful 💫', 'Nice', 'Love this'],
  },
  {
    id: 6,
    catg: 'couple',
    name: 'ForeverUs',
    iconImage: 'https://i.pravatar.cc/150?img=6',
    deatail: 'Some moments are worth keeping forever ❤️',
    postImage: 'https://picsum.photos/800/600?random=6',
    likeCount: '643',
    postTime: '3 hours ago',
    comments: ['Forever ❤️', 'So sweet', 'Amazing', 'Best couple'],
  },
  {
    id: 7,
    catg: 'single',
    name: 'WildHeart',
    iconImage: 'https://i.pravatar.cc/150?img=7',
    deatail: 'Life is too short to worry about what people think 🔥',
    postImage: 'https://picsum.photos/800/600?random=7',
    likeCount: '391',
    postTime: '4 hours ago',
    comments: ['Absolutely 🔥', 'Great attitude', 'Love this', 'True'],
  },
  {
    id: 8,
    catg: 'couple',
    name: 'WeekendLove',
    iconImage: 'https://i.pravatar.cc/150?img=8',
    deatail: 'Weekend plans are always better together 🥰',
    postImage: 'https://picsum.photos/800/600?random=8',
    likeCount: '456',
    postTime: '5 hours ago',
    comments: ['Cute ❤️', 'Nice couple', 'Beautiful', 'Enjoy guys'],
  },
  {
    id: 9,
    catg: 'single',
    name: 'DreamGirl',
    iconImage: 'https://i.pravatar.cc/150?img=9',
    deatail: 'Dream big, smile bigger ✨',
    postImage: 'https://picsum.photos/800/600?random=9',
    likeCount: '215',
    postTime: '6 hours ago',
    comments: ['Beautiful smile', 'Nice ✨', 'Looking great', 'Wow'],
  },
  {
    id: 10,
    catg: 'couple',
    name: 'PerfectMatch',
    iconImage: 'https://i.pravatar.cc/150?img=10',
    deatail: 'Together is our favorite place to be 💕',
    postImage: 'https://picsum.photos/800/600?random=10',
    likeCount: '735',
    postTime: '8 hours ago',
    comments: ['Perfect match ❤️', 'So cute', 'Beautiful couple', 'Amazing'],
  },
  {
    id: 11,
    catg: 'single',
    name: 'MidnightQueen',
    iconImage: 'https://i.pravatar.cc/150?img=11',
    deatail: 'Late night thoughts and good vibes 🌙',
    postImage: 'https://picsum.photos/800/600?random=11',
    likeCount: '367',
    postTime: '10 hours ago',
    comments: ['Good vibes 🌙', 'Looking beautiful', 'Nice pic', 'Love it'],
  },
  {
    id: 12,
    catg: 'couple',
    name: 'SweetTogether',
    iconImage: 'https://i.pravatar.cc/150?img=12',
    deatail: 'Collecting beautiful memories together ❤️',
    postImage: 'https://picsum.photos/800/600?random=12',
    likeCount: '298',
    postTime: '12 hours ago',
    comments: ['Beautiful memories', 'So sweet', 'Lovely ❤️', 'Amazing'],
  },
  {
    id: 13,
    catg: 'single',
    name: 'SunshineGirl',
    iconImage: 'https://i.pravatar.cc/150?img=13',
    deatail: 'A little sunshine can change everything ☀️',
    postImage: 'https://picsum.photos/800/600?random=13',
    likeCount: '421',
    postTime: '15 hours ago',
    comments: ['Beautiful ☀️', 'Love your smile', 'Amazing', 'Nice'],
  },
  {
    id: 14,
    catg: 'couple',
    name: 'TwoHearts',
    iconImage: 'https://i.pravatar.cc/150?img=14',
    deatail: 'Every love story is beautiful, but ours is my favorite 💖',
    postImage: 'https://picsum.photos/800/600?random=14',
    likeCount: '856',
    postTime: '18 hours ago',
    comments: ['Beautiful love ❤️', 'So cute', 'Best couple', 'Lovely'],
  },
  {
    id: 15,
    catg: 'single',
    name: 'QueenVibes',
    iconImage: 'https://i.pravatar.cc/150?img=15',
    deatail: 'Confidence looks good on everyone 👑',
    postImage: 'https://picsum.photos/800/600?random=15',
    likeCount: '534',
    postTime: '1 day ago',
    comments: ['Queen 👑', 'Looking amazing', 'Beautiful', 'Great vibes'],
  },
  {
    id: 16,
    catg: 'couple',
    name: 'LoveStory',
    iconImage: 'https://i.pravatar.cc/150?img=16',
    deatail: 'Every day feels special when I am with you 💕',
    likeCount: '612',
    postTime: '1 day ago',
    comments: ['So romantic ❤️', 'Beautiful', 'Cute couple', 'Amazing'],
  },
  {
    id: 17,
    catg: 'single',
    name: 'JustMe',
    iconImage: 'https://i.pravatar.cc/150?img=17',
    deatail: 'No filter, just me and my vibes ✨',
    postImage: 'https://picsum.photos/800/600?random=17',
    likeCount: '346',
    postTime: '2 days ago',
    comments: ['Natural beauty', 'Looking good', 'Nice ✨', 'Love it'],
  },
  {
    id: 18,
    catg: 'couple',
    name: 'TogetherForever',
    iconImage: 'https://i.pravatar.cc/150?img=18',
    deatail: 'Making memories one day at a time 💕',
    postImage: 'https://picsum.photos/800/600?random=18',
    likeCount: '924',
    postTime: '2 days ago',
    comments: ['Forever ❤️', 'Beautiful couple', 'So sweet', 'Amazing'],
  },
  {
    id: 19,
    catg: 'single',
    name: 'FreeSpirit',
    iconImage: 'https://i.pravatar.cc/150?img=19',
    deatail: 'Be yourself. Everyone else is already taken 🔥',
    postImage: 'https://picsum.photos/800/600?random=19',
    likeCount: '489',
    postTime: '3 days ago',
    comments: ['Absolutely 🔥', 'Great quote', 'Looking good', 'True words'],
  },
  {
    id: 20,
    catg: 'couple',
    name: 'HappyTogether',
    iconImage: 'https://i.pravatar.cc/150?img=20',
    deatail: 'Good moments become great memories when shared together ❤️',
    postImage: 'https://picsum.photos/800/600?random=20',
    likeCount: '578',
    postTime: '4 days ago',
    comments: ['Beautiful ❤️', 'Cute couple', 'Lovely', 'Amazing picture'],
  },
];

export default postData;